#! /bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

IMG="${IMG:-artifacts/mutuatechlinux-general-cachyos-x86_64_v4.img}" \
TARGET_ARCH="${TARGET_ARCH:-x86_64_v4}" \
XZ_LEVEL="${XZ_LEVEL:-1}" \
../common/publish_image
