#! /bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# pre-requisites: the host must have the following packages installed
# pacman -S --needed qemu-user-static qemu-user-static-binfmt
# and must execute this before this script (if the above was installed after the last reboot)
# sudo /usr/lib/systemd/systemd-binfmt
# after this script, you may restore the previous state with
# sudo /usr/lib/systemd/systemd-binfmt --unregister && pacman -Rsc qemu-user-static qemu-user-static-binfmt

# --- Default Settings ---
mkdir -p artifacts
IMG="${IMG:-artifacts/mutuatechlinux-general-aarch64.img}"
IMG_SIZE="${IMG_SIZE:-6G}"
ESP_SIZE="${ESP_SIZE:-4MiB}"
SWAP_SIZE="${SWAP_SIZE:-1GiB}"
HOST_AUTH_KEYS="${HOST_AUTH_KEYS:-$HOME/.ssh/authorized_keys}"  # copied to root
FS_LABEL="${FS_LABEL:-mtl_root}"
TARGET_ARCH="${TARGET_ARCH:-aarch64}"
ROOT_PW="${ROOT_PW:-mutuatechlinux}"  # optional; if empty, root password stays locked
DEF_USER="${DEF_USER:-}"              # e.g. 'arch'
DEF_USER_PW="${DEF_USER_PW:-}"        # optional

BASE_PKGS=(base base-devel linux-aarch64 linux-firmware btrfs-progs compsize jemalloc gptfdisk parted mkinitcpio-nfs-utils cloud-guest-utils wget grub efibootmgr net-tools dhclient openssh openbsd-netcat less vim sudo rust archlinux-keyring archlinuxarm-keyring dosfstools arch-install-scripts)
ONLINE_PACKAGES=()
CUSTOM_CACHE_BASE_URL="http://mutuatech.com/MutuatechLinux/cache/aarch64"
CUSTOM_CACHE_PACKAGE_FILES=(
  'mutuatechlinux-general-multiarch-1.1.41-1-aarch64.pkg.tar.xz'
  'paru-bin-2.1.0-1-aarch64.pkg.tar.xz'
)
CUSTOM_CACHE_REQUIRED_PATTERNS=(
  'mutuatechlinux-general-multiarch-*-aarch64.pkg.tar.*'
  'paru-bin-*-aarch64.pkg.tar.*'
)
PARTITION_FN=create_and_partition_image_gpt
BOOTSTRAP_FN=bootstrap_emulated
SYNC_PACMAN_CACHE=1
PRE_FLIGHT_FN=preflight_emulated_aarch64_build
PUBLISH_IMAGE_HINT="./publish_aarch64_image"
TEST_IMAGE_HINT="./test_image"
INNER_SCRIPT="./image_setup_inner_script"
COMMON_FILES_DIR="../common/files"

. ../common/build_image

# NOTES
# 1) To update the cache, chroot into the image and update the packages, then scp -pr cache/* mutuatec@mutuatech.com:~/public_html/MutuatechLinux/cache/aarch64/
# 2) After updating the cache, update the package names being fetched to the cache above in this script
# 3) To enter the chroot image, just add a line containing 'debug' between any of the above steps
# 4) To chroot on the final image, execute:
# IMG="artifacts/mutuatechlinux-general-aarch64.img"; LOOPDEV="$(sudo losetup --find --show -P "$IMG")"; sudo partprobe "$LOOPDEV"; P1="${LOOPDEV}p1"; P2="${LOOPDEV}p2"; P3="${LOOPDEV}p3"; MNT="$(mktemp -d)"; sudo mount -o compress-force=zstd:15,space_cache=v2,noatime "$P3" "$MNT"; sudo mkdir -p "$MNT/boot/efi"; sudo mount "$P1" "$MNT/boot/efi"; sudo arch-chroot "$MNT"; sudo umount -l "$MNT/boot/efi"; sudo umount -l "$MNT"; sudo losetup -d "$LOOPDEV"; sudo rmdir "$MNT"
