#! /bin/bash
set -euo pipefail

# --- Default Settings ---
mkdir -p artifacts
IMG="${IMG:-artifacts/mutuatechlinux-general-aarch64.img}"
IMG_SIZE="${IMG_SIZE:-4G}"
ESP_SIZE="${ESP_SIZE:-4MiB}"
SWAP_SIZE="${SWAP_SIZE:-1GiB}"
HOST_AUTH_KEYS="${HOST_AUTH_KEYS:-$HOME/.ssh/authorized_keys}"  # copied to root
FS_LABEL="${FS_LABEL:-mtl_root}"
ROOT_PW="${ROOT_PW:-mutuatechlinux}"  # optional; if empty, root password stays locked
DEF_USER="${DEF_USER:-}"              # e.g. 'arch'
DEF_USER_PW="${DEF_USER_PW:-}"        # optional

# load the building functions
. ../common/image_build_lib
require_commands sgdisk sfdisk losetup mkfs.fat mkswap mkfs.btrfs pacstrap arch-chroot genfstab grub-install grub-mkconfig partprobe


BASE_PKGS=(base base-devel linux-aarch64 linux-firmware btrfs-progs compsize gptfdisk parted mkinitcpio-nfs-utils cloud-guest-utils wget grub efibootmgr net-tools dhclient openssh openbsd-netcat vim sudo rust archlinux-keyring archlinuxarm-keyring dosfstools arch-install-scripts)
ONLINE_PACKAGES=()

fetch_custom_pkgs_cache http://mutuatech.com/MutuatechLinux/cache/aarch64/{mutuatechlinux-general-multiarch-1.1.41-1-aarch64.pkg.tar.xz,paru-bin-2.1.0-1-aarch64.pkg.tar.xz}
create_and_partition_image
format_and_mount_partitions
bootstrap_emulated
debug # go there and see where the files got downloaded. Bring them to the local cache pacman directory, to be restored after this step
generate_fstab
execute_inner_script "./image_setup_inner_script"
adjust_grub
copy_image_files ../common/files
setup_sshd_and_keys
setup_root_and_users
zeroize
ready_msg

# NOTES
# 1) To update the cache, chroot into the image and update the packages, then scp -pr cache/* mutuatec@mutuatech.com:~/public_html/MutuatechLinux/cache/aarch64/
# 2) After updating the cache, update the package names being fetched to the cache above in this script
# 3) To enter the chroot image, just add a line containing 'debug' between any of the above steps
# 4) To chroot on the final image, execute:
IMG="artifacts/mutuatechlinux-general-aarch64.img"; LOOPDEV="$(sudo losetup --find --show -P "$IMG")"; sudo partprobe "$LOOPDEV"; P1="${LOOPDEV}p1"; P2="${LOOPDEV}p2"; P3="${LOOPDEV}p3"; MNT="$(mktemp -d)"; sudo mount -o compress-force=zstd:15,space_cache=v2,noatime "$P3" "$MNT"; sudo mkdir -p "$MNT/boot/efi"; sudo mount "$P1" "$MNT/boot/efi"; sudo arch-chroot "$MNT"; sudo umount -l "$MNT/boot/efi"; sudo umount -l "$MNT"; sudo losetup -d "$LOOPDEV"; sudo rmdir "$MNT"
