#! /bin/bash

ROOT="img_root_bootstrap/";
INNER_SCRIPT="image_setup_script";

sudo rm -fr "${ROOT}"
sudo mkdir "${ROOT}"

echo "1) Downloading the cached packages"
mkdir cache &&
cd cache &&
wget -c http://mutuatech.com/MutuatechLinux/cache/aarch64/{mutuatechlinux-general-multiarch-1.1.41-1-aarch64.pkg.tar.xz,paru-bin-2.1.0-1-aarch64.pkg.tar.xz}
cd .. 

echo "2) Building the image"
sudo pacstrap -C ./alarm-pacman.conf -M -G -K "${ROOT}" base linux-aarch64 linux-firmware btrfs-progs openssh sudo archlinux-keyring archlinuxarm-keyring &&

sudo cp -a "${INNER_SCRIPT}" "${ROOT}/root" &&
sudo cp -a cache/* "${ROOT}/tmp/" &&
sudo mkdir -p img_root/ &&
echo "|||| ABOUT TO MOUNT" &&
echo sudo mount --bind "${ROOT}" img_root/ &&
sudo mount --bind "${ROOT}" img_root/ &&
echo "|||| ABOUT TO CHROOT" &&
sudo arch-chroot img_root/ /bin/bash -c ". /root/${INNER_SCRIPT} && rm /root/${INNER_SCRIPT} || echo '** FAILED EXECUTING INNER SCRIPT (see above logs)'" &&
echo "## DONE" || echo "## FAILED (see above logs)"

echo "3) Cleaning building left-overs"
sudo umount img_root/ &&
sudo rmdir img_root/ &&
echo "## CLEANED" || echo "## FAILED CLEANING (see above logs)"

echo "4) Packaging"

# NOTES
# 1) To update the cache, chroot into the image and update the packages, then scp -pr cache/* mutuatec@mutuatech.com:~/public_html/MutuatechLinux/cache/aarch64/
# 2) After updating the cache, update the package names above in this script
