#! /bin/bash

IMG="./artifacts/mutuatechlinux-general-aarch64.img"
INITRD_SCRIPTS="../common/initrd_installer/initcpio"
ARTIFACTS="./artifacts"
TARGET_ARCH="${TARGET_ARCH:-aarch64}"
KERNEL_PKG="${KERNEL_PKG:-linux-${TARGET_ARCH}}"


. ../common/initrd_installer/generate_initrd_installer
