#! /bin/bash

echo "LOCAL clean -- please, remove older duplucates with rm:"
ls -1rt *.pkg.tar* | while read l; do p=`pacman -Q -p ${l} | sed 's| .*||'`; echo "$p"; done | sort -u | while read p; do c=`ls -1 ${p}-[0-9vrlb][0-9:\.aeu-]* | wc -l`; if ((c > 1)); then echo "## $((c)) - $p:"; ls -l ${p}-[0-9vrlb][0-9:\.aeu-]*; fi; done
echo "REMOTE clean -- please, remove older duplicates with lftp and then rm:"
lftp ftp://linux\@mutuatech.com:mutuatech@mutuatech.com -e "set ssl:verify-certificate false; set ftp:ssl-allow false; set ftp:list-options; setftp:proxy ${ftp_proxy}; cd aur; ls -1 *.pkg.tar*; quit" >/tmp/.mtlpkgs$$; cat /tmp/.mtlpkgs$$ | sed 's|-[0-9vrlb][0-9:\.aeu-][0-9-].*||' | sort -u | while read p; do c=`grep ^${p}-[0-9vrlb][0-9:\.aeu-][0-9-] /tmp/.mtlpkgs$$ | wc -l`; if ((c > 1)); then echo "## $((c)) - $p:"; grep ^${p}-[0-9vrlb][0-9:\.aeu-][0-9-] /tmp/.mtlpkgs$$; fi; done; rm /tmp/.mtlpkgs$$
