#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

IMG="${IMG:-${SCRIPT_DIR}/../artifacts/mutuatechlinux-general-x86_64.img}"
INITRD_SCRIPTS="${INITRD_SCRIPTS:-${SCRIPT_DIR}/../../common/initrd_installer/initcpio}"
ARTIFACTS="${ARTIFACTS:-${SCRIPT_DIR}/artifacts}"

. "${SCRIPT_DIR}/../../common/initrd_installer/generate_initrd_installer"
