#! /bin/bash

# This script is designed to merge any changes done in scripts, documentations and other contents that reside in '../files'
# the visual tool 'xxdiff' was elected into assisting this procedure.

# Remember that any changes merged into '/home/common' should be checked and applyed in each user's home

# files in /home/common and ../files/home/common
COMMON_FILES=(
    bin/
    sbin/
    jwmrc
    startcompiz
    xinitrc
    bash_logout
    bash_profile
    bashrc
)

ROOT_FILES=(
    root/.bash_profile
    root/mvuser
    root/bin/
    etc/modules-load.d/anbox.conf
    etc/modprobe.d/mutuatechlinux.conf
    etc/default/tlp
    etc/sudoers
    etc/systemd/swap.conf
    etc/systemd/system/getty@tty1.service.d/autologin.conf
    etc/sysctl.d/99-sysctl.conf
)

# diff common files
for f in "${COMMON_FILES[@]}"; do
    xxdiff "../files/home/common/$f" "/home/common/$f"
done

# diff root files
xhost +
for f in "${ROOT_FILES[@]}"; do
    sudo QT_X11_NO_MITSHM=1 xxdiff "../files/$f" "/$f"
done
