#! /bin/bash

# This script is designed to merge any changes done in the linking structure of '/home/new_user' (and, consequently, on '/home/common' directories).

# For file & content comparisons, please see 'SyncFiles'.

# Remember that any changes merged into '/home/common' and '/home/new_user' should be checked and applyed in each user's home.

# Also remember that, since we use a command to generate 'new_user.current.file_list', the feature "Redo diff" from 'xxdiff' won't work for changes done in '/home/new_user'

find /home/new_user/ -maxdepth 2 -type l -ls | sed 's|[^/]*/home/||' | sort >/tmp/new_user.current.file_list
xxdiff ../new_user.file_list /tmp/new_user.current.file_list
rm /tmp/new_user.current.file_list
