#! /bin/bash

# Use this script to check which packages you need to install or may remove in order to mirror the original "Mutuatech Linux" package list.

# Note: AUR packages starts with _

# To actually sync the packages, use the following command:
# . ./SyncPackages | sort -u >/tmp/sorted_unique_script_packages; pacman -Q | while read l; do p=${l/[^A-Za-z0-9_\.+-]*/}; if pacman -Qi $p | grep -i "xplicit" &>/dev/null; then if pacman -Si $p &>/dev/null; then echo "arch: $p"; else echo "AUR: $p"; fi; fi; done | tee /tmp/explicit_installed_packages; sort /tmp/explicit_installed_packages >/tmp/sorted_explicit_installed_packages; xxdiff /tmp/sorted_unique_script_packages /tmp/sorted_explicit_installed_packages

# Useful commands:
# 1) List missing packages:
#   echo "## From Main Repositories:"; for p in `. ./SyncPackages | grep 'arch: ' | sed 's|arch: ||'`; do if pacman -Q $p &>/dev/null; then true; else echo "$p NOT INSTALLED"; fi; done; echo "## From AUR:"; for p in `. ./SyncPackages | grep 'AUR: ' | sed 's|AUR: ||'`; do if pacman -Q $p &>/dev/null; then true; else echo "$p NOT INSTALLED"; fi; done

BASE=(

    ## basic softwarex

    hunspell
    hunspell-en
    _hunspell-pt-br
    bluez-utils
    bzip2
    cpupower
    dosfstools
    e2fsprogs
    ethtool
    fakeroot
    git
    hdparm
    i7ze
    intel-ucode
    iotop
    linux-headers
    libopenraw
    _mkbold-mkitalic
    mlocate
    net-tools
    _packer
    pkgfile
    powertop
    recordmydesktop
    screen
    sdparm
    squashfs-tools
    systemd-swap
    unrar
    unzip
    usb_modeswitch
    wget
    wireless_tools
    _woff2-git
    x264

    # printing
    cups
    foomatic-db-engine

    # drivers
    vulkan-intel

    # UI control
    wmctrl
    xorg-xbacklight
    xdotool
    _xmacro

    # UI
    gdmap
    gkrellm         # cool system monitor
    gparted
    gsmartcontrol
    gvim
    pavucontrol
    tlpui
    xarchiver
    xdiskusage
    xorg-xinput
    xorg-xwininfo
    _xxdiff
    _xlunch-git

    ## android
    android-tools
    android-udev 

    # joe's window manager
    jwm
    jwm-artwork
    jwm-documentation
    jwm-wallpapers
    jwmconf
    jwmtools
    # manjaro-jwm-settings  # conflicts with manjaro-deepin-settings
    pacli-jwm
    xdgmenumaker

)

DEV=(

    # databases
    mysql
    postgresql

    # database UI
    pgadmin4
    dbeaver
    _oracle-datamodeler
    _oracle-sqldeveloper

    # web / frontend
    hugo

    # diagrams & plotting
    gnuplot
    gdb
    _ddd
    jad
    dia
    _modelio-bin

    # version control
    subversion
    _smartgit

    # xml
    _editix-free

    # android
    _android-sdk

    # c
    automake

    # dotnet core
    _dotnet-sdk-2.0

    # java
    _jdk
    jadx
    _jmeter
    proguard
    maven
    _soapui

    # java servers
    tomcat8
    tomcat-native
    _wildfly

    # javascript
    bower
    gulp
    npm
    yarn
    typescript

    # other languages
    r
    glpk

    # IDEs & editors
    atom
    _sublime-text-dev
    _visual-studio-code-bin
    eclipse-jee
    _eclipse-subclipse
    _eclipse-pmd
    _eclipse-umlet
    netbeans
    _intellij-idea-ultimate-edition
    _android-studio
    _rstudio-desktop-bin

    # hacking / forensic
    wireshark-gtk
    foremost
    testdisk
    heimdall        # android

)

IMAGING=(
    
    ghostscript

    # UI
    gimp
    gutenprint
    inkscape
    scribus
    blender
    _font-manager
    _fontforge

    ## fonts
    gsfonts
    noto-fonts
    otf-overpass
    _ttf-ms-fonts      _ttf-vista-fonts     font-bh-ttf     ttf-arphic-uming     ttf-baekmuk     ttf-bitstream-vera     ttf-cheapskate     ttf-arphic-ukai     ttf-croscore
    ttf-dejavu     ttf-droid     ttf-fira-mono     ttf-freefont     ttf-gentium     ttf-hack     ttf-ionicons     ttf-junicode     ttf-liberation     ttf-linux-libertine
    ttf-linux-libertine-g     ttf-tibetan-machine     ttf-ubraille     ttf-ubuntu-font-family
    _ttf-thelinuxbox-fonts  _ephifonts

    # AUR fonts
    _cl-zpb-ttf _minecrafter-ttf _neuropol-ttf _otf-zilla-slab _terminus-font-ll2-td1-ttf _tgl-ttf _ttf-14minute _ttf-abibas _ttf-abkai _ttf-alef-ibx _ttf-all-the-icons _ttf-animeace _ttf-anonymice-powerline-git 
    _ttf-antinoou _ttf-arphic _ttf-arphic-extra _ttf-atom-file-icons _ttf-au _ttf-averia-libre _ttf-averia-serif _ttf-babel-sans _ttf-barcodes _ttf-belligerent-madness _ttf-berylium-fonts _ttf-blackout
    _ttf-blogger-sans _ttf-borders-divide-fonts _ttf-c64-fonts _ttf-camingocode _ttf-campus_relief _ttf-ceva-c2 _ttf-ceva-cm _ttf-chunk _ttf-cica _ttf-comfortaa _ttf-comme _ttf-conkyweather 
    _ttf-contemporary _ttf-coolvetica _ttf-cutive-mono _ttf-dasroy _ttf-ddc-uchen _ttf-dejavu-sans-code _ttf-digital-7 _ttf-din1451 _ttf-djb-zora-prints-fonts _ttf-dosega 
    _ttf-droid-sans-mono-dotted-powerline-git _ttf-dseg _ttf-dugfont _ttf-economica _ttf-enochian _ttf-eurostile-complete _ttf-fanwood _ttf-fate-core _ttf-fixedsys-excelsior-linux _ttf-font-awesome 
    _ttf-font-linux _ttf-free3of9 _ttf-funfonts _ttf-futhark-adapted _ttf-fuzzy-cootie _ttf-google-fonts-typewolf _ttf-goudy-bookletter-1911 _ttf-gurmukhi-fonts_sikhnet _ttf-gurmukhi_punjabi 
    _ttf-hack-ibx _ttf-i.bming _ttf-ifao-n-copte _ttf-impallari-cancelleresca-bastarda _ttf-impallari-hermeusone _ttf-impallari-libre-caslon-display _ttf-impallari-milonga 
    _ttf-impallari-neuton-serif-family _ttf-impallari-new-rocker _ttf-impallari-poetsen-one _ttf-impallari-racing-sans _ttf-impallari-ranchers _ttf-impallari-sniglet _ttf-invader _ttf-indic-otf _ttf-iosevka-cc 
    _ttf-iosevka-cc-slab _ttf-iosevka-ss07 _ttf-iosevka-term-ss07 _ttf-istok _ttf-jenna-sue _ttf-jomolhari _ttf-junction _ttf-keep-calm-medium _ttf-kix _ttf-klingon-piqad-hasta _ttf-klingon-piqad-mandel 
    _ttf-klingon-piqad-vahbo _ttf-knewave _ttf-lacartoonerie _ttf-lastresort _ttf-lastwaerk _ttf-lazenby-computer _ttf-league-gothic _ttf-league-spartan _ttf-liberastika _ttf-lightfoot 
    _ttf-linden-hill _ttf-linek _ttf-linex-fonts _ttf-london-tube _ttf-lora-cyrillic _ttf-manaspace _ttf-masterforce-solid _ttf-material-wifi-icons-git _ttf-maven-pro _ttf-monda _ttf-monofur-powerline-git 
    _ttf-montepetrum _ttf-ms-fonts _ttf-muli _ttf-neverworld _ttf-new-athena-unicode _ttf-niceandripe _ttf-noto-fonts-emoji-ib _ttf-nunito _ttf-octicons _ttf-oldenglish5 _ttf-openwebicons 
    _ttf-optimusprinceps _ttf-orbitron _ttf-ostrich-sans _ttf-oxygen-gf _ttf-pfennig-ibx _ttf-play _ttf-press-start-2p _ttf-prociono _ttf-profont-iix _ttf-roboto-mono-ibx _ttf-saginaw _ttf-sansation-ibx 
    _ttf-sazanami-hanazono _ttf-sf_groove_machine _ttf-share-gf _ttf-signika-family-ib _ttf-sil-abyssinica _ttf-sinkin-sans-ibx _ttf-sorts-mill-goudy _ttf-sorts-mill-goudy-ibx _ttf-source-code-pro-ibx 
    _ttf-sparks-ffa _ttf-sparks-scrapbook _ttf-sudo _ttf-symbola-ib _ttf-ti83symbols _ttf-timetable-latest _ttf-traveling-typewriter _ttf-triod-postnaja-ibx _ttf-typicons _ttf-typopro 
    _ttf-ubuntu-mono-derivative-powerline-git  _ttf-vdrsymbols _ttf-vista-fonts _ttf-vollkorn-ibx _ttf-webhostinghub-glyphs _ttf-whiterabbit _ttf-wireone _ttf-wqy-microhei-ibx _ttf-xo-caliburn 
    _ttf-xo-courser _ttf-xo-oriel _ttf-xo-symbol _ttf-xo-symbol-mac _ttf-xo-tahion _ttf-xo-thames _ttf-xo-windy _ttf-x-scale _ttf-yanone-kaffeesatz-ibx _ttf-yas _ttf-zekton-rg _ttf-zelda _ttf-zilla-slab


)

VIRTUALIZATION=(

    ## PC
    virtualbox
    virtualbox-guest-utils
    virtualbox-guest-dkms
    _virtualbox-ext-oracle

    # docker
    docker-compose
    docker-machine

    # android
    _genymotion
    _anbox-git

    # wine
    playonlinux
)

MULTIMEDIA=(

    # libs    
    _gst-plugin-libde265
    _libde265
    gst-libav
    gst-plugins-bad
    gst-plugins-base
    gst-plugins-good
    gst-plugins-ugly

    # browser plugins
    gstreamer-vaapi
    flashplugin
    pepper-flash

    # command-line
    youtube-dl
    mplayer

    # UI
    deadbeef
    vlc
    handbrake
    ardour      # multitrack audio editor
    audacity    # waveform audio editor
    guitarix2
    _tuxguitar
    hydrogen    # drums
)

NETWORKING=(

    # servers
    lighttpd

    # console tools
    _cntlm              # Conectivity with Microsoft's NTLM Proxy
    arp-scan
    netcat
    smbclient
    nmap                # network discovery
    iw

    # command line file transfer clients
    aria2
    lftp

    # UI
    _brave-bin
    chromium
    firefox
    firefox-developer-edition
    midori
    opera
    _opera-ffmpeg-codecs
    qupzilla
    seamonkey
    surf
    _vivaldi
    _vivaldi-ffmpeg-codecs

    # email
    thunderbird

    # remote clients
    tigervnc
    rdesktop
    _icaclient  # citrix

    # conferencing
    _skype
    _lib32-apulse
    _zoom

    # multiprotocol messaging
    _franz-bin

)

OFFICE=(

    libreoffice-fresh

    # diagramming
    gephi
    _astah-community        # uml
    _yed                    # graph

    # mind mapping
    vym
    freemind
    _freeplane

    ## management
    _ganttproject
    _projectlibre
    _treesheets-git


    # pdf reader
    _acroread
    _acroread-fonts-systemwide

)

CAD=(

    qcad
    
    # 3D solid CAD modelers
    openscad
    freecad

    # interior & forniture disposition planning
    sweethome3d
    _sweethome3d-furniture-library

)

AMUSEMENT=(
    
    # the universe
    celestia
    stellarium

    # 3D games
    armagetronad
    astromenace
    supertuxkart
    _darkmod
    _openarena
    _voxelands

    # 2D games
    blobwars
    hedgewars
    wesnoth
    wesnoth-data
    widelands

)

HAND_INSTALLED=(

    # pentaho
    /opt/pentaho/data-integration
    /opt/pentaho/metadata-editor
    /opt/pentaho/pentaho-server
    /opt/pentaho/report-designer

    # android SDK (via android-studio)
    /opt/android...

)

PACKAGES=( "${BASE[@]}" "${DEV[@]}" "${IMAGING[@]}" "${VIRTUALIZATION[@]}" "${MULTIMEDIA[@]}" "${NETWORKING[@]}" "${OFFICE[@]}" "${CAD[@]}" "${AMUSEMENT[@]}" )


for i in "${PACKAGES[@]}"; do
    echo "${i}" | sed 's|^\([^_]\)|arch: \1|' | sed 's|^_|AUR: |'
done

# Windows users should install Chocolatey and use the following packages:
# 7zip adb adobereader advanced-codecs dbeaver eclipse ffmpeg freeplane gimp git GoogleChrome
# googleearthpro InkScape jdk8 jmeter libreoffice-fresh musicbee nodejs putty scribus sublimetext3
# sysinternals thunderbird tightvnc treesizefree virtualbox visualstudiocode vlc wireshark yarn
# yed youtube-dl

# win 10 save
7zip v18.1 is the latest version available based on your source(s).
7zip.install v18.1 is the latest version available based on your source(s).
adb v1.0.39.20171026 is the latest version available based on your source(s).
adobereader v2015.007.20033.02 is the latest version available based on your source(s).
advanced-codecs v8.9.0 is the latest version available based on your source(s).
autohotkey v1.1.28.00 is the latest version available based on your source(s).
autohotkey.install v1.1.28.00 is the latest version available based on your source(s).
autohotkey.portable v1.1.28.00 is the latest version available based on your source(s).
chocolatey v0.10.9 is the latest version available based on your source(s).
chocolatey-core.extension v1.3.3 is the latest version available based on your source(s).
chocolatey-visualstudio.extension v1.6.0 is the latest version available based on your source(s).
chocolatey-windowsupdate.extension v1.0.2 is the latest version available based on your source(s).
chocolatey v0.10.9 is the latest version available based on your source(s).
chocolateygui v0.16.0 is the latest version available based on your source(s).
dbeaver v5.0.1 is the latest version available based on your source(s).
DotNet3.5 v3.5.20160716 is the latest version available based on your source(s).
DotNet4.5.2 v4.5.2.20140902 is the latest version available based on your source(s).
DotNet4.6.1 v4.6.01055.20170308 is the latest version available based on your source(s).
dotnetcore-sdk v2.1.102 is the latest version available based on your source(s).
eclipse v4.7.3 is the latest version available based on your source(s).
ffmpeg v3.4.2 is the latest version available based on your source(s).
freeplane v1.6.14 is the latest version available based on your source(s).
Ghostscript v9.23 is the latest version available based on your source(s).
Ghostscript.app v9.23 is the latest version available based on your source(s).
gimp v2.8.22.20171021 is the latest version available based on your source(s).
git v2.16.3 is the latest version available based on your source(s).
git.install v2.16.3 is the latest version available based on your source(s).
GoogleChrome v65.0.3325.18100 is the latest version available based on your source(s).
googleearthpro v7.3.1.4507 is the latest version available based on your source(s).
javaruntime v8.0.151 is the latest version available based on your source(s).
jdk8 v8.0.162 is the latest version available based on your source(s).
jmeter v4.0 is the latest version available based on your source(s).
jre8 v8.0.161 is the latest version available based on your source(s).
KB2533623 v1.0.2 is the latest version available based on your source(s).
KB2919355 v1.0.20160915 is the latest version available based on your source(s).
KB2919442 v1.0.20160915 is the latest version available based on your source(s).
KB2999226 v1.0.20170509 is the latest version available based on your source(s).
KB3033929 v1.0.3 is the latest version available based on your source(s).
KB3035131 v1.0.1 is the latest version available based on your source(s).
libreoffice-fresh v6.0.2 is the latest version available based on your source(s).
MsSqlServer2014Express v12.2.5000.20170905 is the latest version available based on your source(s).
MsSqlServerManagementStudio2014Express v12.2.5000.20170905 is the latest version available based on your source(s).
musicbee v3.1.6590 is the latest version available based on your source(s).
nodejs v9.9.0 is the latest version available based on your source(s).
nodejs.install v9.9.0 is the latest version available based on your source(s).
projectlibre.portable v1.7 is the latest version available based on your source(s).
putty v0.70.0.20171219 is the latest version available based on your source(s).
putty.portable v0.70.0.20171219 is the latest version available based on your source(s).
scribus v1.4.6.20170429 is the latest version available based on your source(s).
sketchup v2016.1.1449.20170912 is the latest version available based on your source(s).
sublimetext3 v3.0.0.3143 is the latest version available based on your source(s).
sysinternals v2018.2.13 is the latest version available based on your source(s).
thunderbird v52.7.0 is the latest version available based on your source(s).
tightvnc v2.8.8 is the latest version available based on your source(s).
treesizefree v4.1.2.3 is the latest version available based on your source(s).
vcredist140 v14.12.25810 is the latest version available based on your source(s).
vcredist2008 v9.0.30729.6161 is the latest version available based on your source(s).
vcredist2010 v10.0.40219.2 is the latest version available based on your source(s).
vcredist2012 v11.0.61031 is the latest version available based on your source(s).
vcredist2015 v14.0.24215.20170201 is the latest version available based on your source(s).
virtualbox v5.2.8 is the latest version available based on your source(s).
visualstudio2017-installer v1.0.1 is the latest version available based on your source(s).
visualstudio2017community v15.2.26430.20170605 is the latest version available based on your source(s).
visualstudiocode v1.21.1 is the latest version available based on your source(s).
winrar v5.50 is the latest version available based on your source(s).
wireshark v2.4.5 is the latest version available based on your source(s).
yarn v1.5.1 is the latest version available based on your source(s).
yed v3.17.2 is the latest version available based on your source(s).
youtube-dl v2018.03.20 is the latest version available based on your source(s).
