#! /bin/bash

# Replaces our package files with any local changes, so the repository may be sync'ed with the latest changes

# general
cd general
find . -type f | while read f; do
    sudo cp -av "/$f" "$f" && sudo chown $USER "$f"
done
cd -

# desktop
cd desktop
find . -type f | while read f; do
    sudo cp -av "/$f" "$f" && sudo chown $USER "$f"
done
cd -
